// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDCuVFyQRvLAdxunfFaoWGlZ2MrVw0dU',
    appId: '1:909970248044:web:45311dca81bb3db40ea349',
    messagingSenderId: '909970248044',
    projectId: 'app-proyecto-final-s7',
    authDomain: 'app-proyecto-final-s7.firebaseapp.com',
    storageBucket: 'app-proyecto-final-s7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkA6o91suD7t8480IwEPe_sIcNvkVadY',
    appId: '1:909970248044:android:a973736186a584bf0ea349',
    messagingSenderId: '909970248044',
    projectId: 'app-proyecto-final-s7',
    storageBucket: 'app-proyecto-final-s7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdkQb-0jz0TKDUA2NSAOqCeRIshaP_32M',
    appId: '1:909970248044:ios:b44fbad9437b14e10ea349',
    messagingSenderId: '909970248044',
    projectId: 'app-proyecto-final-s7',
    storageBucket: 'app-proyecto-final-s7.firebasestorage.app',
    iosBundleId: 'com.example.appProyectoFinalS7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdkQb-0jz0TKDUA2NSAOqCeRIshaP_32M',
    appId: '1:909970248044:ios:b44fbad9437b14e10ea349',
    messagingSenderId: '909970248044',
    projectId: 'app-proyecto-final-s7',
    storageBucket: 'app-proyecto-final-s7.firebasestorage.app',
    iosBundleId: 'com.example.appProyectoFinalS7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpDCuVFyQRvLAdxunfFaoWGlZ2MrVw0dU',
    appId: '1:909970248044:web:0b88148e9af97f3f0ea349',
    messagingSenderId: '909970248044',
    projectId: 'app-proyecto-final-s7',
    authDomain: 'app-proyecto-final-s7.firebaseapp.com',
    storageBucket: 'app-proyecto-final-s7.firebasestorage.app',
  );
}
